plugins:
  duplication:
    enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    checks:
      Similar code:
        enabled: false
      import/extensions:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - 'server/*.js'
    - 'server/**/*.js'
exclude_patterns:
  - node_modules/
  - .nyc_output
  - coverage
  - server/test/
  - client/
  - models/migration
  