checks:
  Similar code:
      enabled: false
      import/extensions:
      enabled: false
  fixme:
    enabled: true
paths:
  - 'server/*.js'
  - 'server/**/*.js'
exclude_paths:
  - node_modules/
  - .nyc_output
  - coverage
  - server/test/
  - client/
