language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=2d8148c3a07d0a93a2d5268616d7a8bba4d5a76b32743757ca740e35a81cb1d6
language: node_js
node_js:
  - "8.12.0"
before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
after_success:
  -npm run nyc
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT