language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=2d8148c3a07d0a93a2d5268616d7a8bba4d5a76b32743757ca740e35a81cb1d6
node_js:
 - "8.12.0"
script:
 - npm run test
after_success:
  - npm run nyc
  - codeclimate-test-reporter < ./coverage/lcov.info
cache:
  directories:
    - 'node_modules'