const Users = [
  {
    id: 1,
    email: 'jonathanwilliams505@gmail.com',
    firstName: 'jonathan',
    lastName: 'Williams',
    password: 'password',
    address: 'No. 2 address road Lagos, Nigeria',
    workAddress: '',
    status: 'verified',
    isAdmin: true,
    createdAt: '2/24/2019',
    updatedAt: '2/24/2019',
  },
  {
    id: 2,
    email: 'panel@gmail.com',
    firstName: 'Panel',
    lastName: 'Williams',
    password: 'password',
    address: '',
    workAddress: 'No. 18 address road MaryLand, Nigeria',
    status: 'unverified',
    isAdmin: false,
    createdAt: '2/24/2019',
    updatedAt: '2/24/2019',
  },
  {
    id: 3,
    email: 'alibaba@gmail.com',
    firstName: 'Alibaba',
    lastName: 'Yusuf',
    password: 'password',
    address: 'No. 2 address road Lagos, Nigeria',
    workAddress: '',
    status: 'verified',
    isAdmin: true,
    createdAt: '2/24/2019',
    updatedAt: '2/24/2019',
  },
  {
    id: 4,
    email: 'alice@gmail.com',
    firstName: 'Alice',
    lastName: 'Adams',
    password: 'password',
    address: '',
    workAddress: '',
    status: 'verified',
    isAdmin: true,
    createdAt: '2/24/2019',
    updatedAt: '2/24/2019',
  },
  {
    id: 5,
    email: 'timi@gmail.com',
    firstName: 'Timi',
    lastName: 'Adams',
    password: 'password',
    address: 'No 20 admans street Lagos Nigeria',
    workAddress: 'No 20 admans street Lagos Nigeria',
    status: 'verified',
    isAdmin: true,
    createdAt: '2/24/2019',
    updatedAt: '2/24/2019',
  },
  {
    id: 6,
    email: 'nathan@gmail.com',
    firstName: 'Williams',
    lastName: 'Adams',
    password: '$2b$08$jqvlFW01BXQI1i.3qzzJIe.NvXCBYSDT/qO6JUJO807k.v0ez67eq',
    address: 'No 20 admans street Lagos Nigeria',
    workAddress: 'No 20 admans street Lagos Nigeria',
    status: 'verified',
    isAdmin: true,
    createdAt: '2/24/2019',
    updatedAt: '2/24/2019',
    token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImZpcnN0TmFtZSI6IkpvbmF0aGFuIiwibGFzdE5hbWUiOiJXaWxsaWFtcyIsImVtYWlsIjoibmF0aGFuQGdtYWlsLmNvbSIsImlhdCI6MTU1NzAzNTQ5OSwiZXhwIjoxNTU3NjQwMjk5fQ.yf9rwW7HiBtUptBoDeRcWNjNvJ2YOhMdxupBs1xdpsI'
  },
  {
    id: 7,
    email: 'preshy@gmail.com',
    firstName: 'Precious',
    lastName: 'Williams',
    password: '$2b$08$xHLSrWpffbXdOWQg70HdKenDCmktI7bTo1TrqVAvqbzRD2r.4Aena',
    address: 'No 20 admans street Lagos Nigeria',
    workAddress: 'No 20 admans street Lagos Nigeria',
    status: 'verified',
    isAdmin: false,
    createdAt: '2/24/2019',
    updatedAt: '2/24/2019',
    token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTU1NzE0MjE0OCwiZXhwIjoxNTU3NzQ2OTQ4fQ.OSeZiWiWJcEAn1AQv5XN7tt5VlgVOk93f_DUE97TVMg'
  }
];

export default Users;
