const Users = [
  {
    id: 1,
    email: 'jonathanwilliams505@gmail.com',
    firstName: 'jonathan',
    lastName: 'Williams',
    password: 'password',
    address: 'No. 2 address road Lagos, Nigeria',
    workAddress: '',
    status: ' verified',
    isAdmin: true,
    createdAt: '2/24/2019',
    updatedAt: '2/24/2019',
  },
  {
    id: 2,
    email: 'panel@gmail.com',
    firstName: 'Panel',
    lastName: 'Williams',
    password: 'password',
    address: '',
    workAddress: 'No. 18 address road MaryLand, Nigeria',
    status: 'unverified',
    isAdmin: false,
    createdAt: '2/24/2019',
    updatedAt: '2/24/2019',
  },
  {
    id: 3,
    email: 'alibaba@gmail.com',
    firstName: 'Alibaba',
    lastName: 'Yusuf',
    password: 'password',
    address: 'No. 2 address road Lagos, Nigeria',
    workAddress: '',
    status: ' verified',
    isAdmin: true,
    createdAt: '2/24/2019',
    updatedAt: '2/24/2019',
  },
  {
    id: 4,
    email: 'alice@gmail.com',
    firstName: 'Alice',
    lastName: 'Adams',
    password: 'password',
    address: '',
    workAddress: '',
    status: ' verified',
    isAdmin: true,
    createdAt: '2/24/2019',
    updatedAt: '2/24/2019',
  },
];

export default Users;
